apiVersion: v1
kind: BuildConfig
metadata:
  name: s2i-nginx-acme
  labels:
    application: s2i-nginx-acme
spec:
  triggers:
    - type: ConfigChange
    - type: ImageChange
      imageChange:
        kind: ImageStreamTag
        name: s2i-nginx:latest
  source:
    type: Git
    git:
      uri: https://github.com/goern/s2i-nginx.git
    ref: acme-it-dev
  strategy:
    type: Docker
    dockerStrategy:
  output:
    to:
      kind: ImageStreamTag
      name: 's2i-nginx-acme:latest'
