apiVersion: v1
kind: BuildConfig
metadata:
  name: s2i-nginx
  labels:
    application: s2i-nginx
spec:
  triggers:
    -
      type: ConfigChange
  runPolicy: Serial
  source:
    type: Git
    git:
      uri: https://github.com/goern/s2i-nginx
  strategy:
    type: Docker
    dockerStrategy:
  output:
    to:
      kind: ImageStreamTag
      name: 's2i-nginx:latest'
  resources:
  postCommit:
